### PR TITLE
Add FC097, FC098, FC099, and FC100 for deprecated mixin usage

### PR DESCRIPTION
**Pull request by tas50**
Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by coderanger** [comment]
Any reason to not make these all one rule?

**Comment by tas50** [comment]
I considered making it one rule, but we'll have deprecation docs linked for these and the remediation for each is going to be different. Also if we ever deprecate a new mixin it would be less than cool to just add another one to the rule randomly. This makes it super explicit what we're checking and what failed. Also if the contents of the supermarket are any judge *very* few people are going to hit any of these. They're barely public APIs that weren't used much outside of Opscode.

**Comment by coderanger** [comment]
I'm mostly just concerned about rule sprawl, but I suppose that ship already sailed :-/

**Comment by tas50** [comment]
The rules are pretty fine grained, but IMO that's a feature not a bug. The tags are where the sprawl needs to be contained. You shouldn't be disabling individual rules you should be disabling tags

**Pull request merged**
