### PR TITLE
use_inline_resources is the default now. Deprecate FC017/057/059 and add FC113

### PR DESCRIPTION
**Pull request by tas50**
Chef 13 enabled use_inline_resources by default, which eliminates the need for several rules and means we need a new rule to check for the inclusion of use_inline_resources.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
This should go in a release of Foodcritic in ~March since Chef 12 goes EOL in April. We'll get it pulled into ChefDK 14.

**Comment by tristanmorgan** [comment]
Sorry but is chef15 a typo?

**Comment by tas50** [comment]
It will cause a failure in Chef 15 so it's tagged with chef15.

**Comment by tristanmorgan** [comment]
Ohh, OK. I saw the "Chef 13 enabled use_inline_resources...", my mistake.

**Comment by tas50** [comment]
Not needed with 13+, will warn in a future Chef 14 release, will fail in 15.0

**Pull request merged**
